language: node_js
node_js: stable
install:
  - npm install
  - git clone https://github.com/changkun/hexo-theme-next themes/next
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "vncnliu"
  - git config user.email "vncnliu@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/vncnliu/vncnliu.github.io.git

cache:
  directories:
    - node_modules